### ISSUE TITLE
Option disable preview window

### ISSUE THREAD

**Issue by MichaelAquilina** [maralla/completor.vim#127]
I cant seem to find a way to disable the preview window to show a functions documentation (I personally find it quite annoying). It either doesnt exist yet, or the option is not documented. Either way it should be fixed :)

**Comment by maralla** [comment]
You can update to the latest commit and use the following config to disable the preview window:
```vim
" vimrc
set completeopt-=preview
```

**Comment by MichaelAquilina** [comment]
Thanks!

**Comment by MichaelAquilina** [comment]
Updated to the latest version but there seems to be an issue:
```
Error detected while processing function <SNR>107_complete[1]..completor#utils#get_completer[1]..prov
ider#python3#Call:                                                                                   
line   18:                                                                                           
Traceback (most recent call last):                                                                   
  File "<string>", line 1, in <module>                                                               
  File "/home/michael/.vim/plugged/completor.vim/pythonx/completor/api.py", line 14, in wrapper      
    return func(vim.bindeval('a:'))                                                                  
  File "/home/michael/.vim/plugged/completor.vim/pythonx/completor/api.py", line 22, in get_completer
                                                                                                     
    return c.get_cmd_info(b'complete') if c else vim.Dictionary()                                    
  File "/home/michael/.vim/plugged/completor.vim/pythonx/completor/__init__.py", line 141, in get_cmd
_info                                                                                                
    return vim.Dictionary(                                                                           
Press ENTER or type command to continue                                                              
Error detected while processing function <SNR>107_complete[1]..completor#utils#get_completer[1]..prov
ider#python3#Call:                                                                                   
line   18:                                                                                           
AttributeError: 'LegacyVim' object has no attribute 'Dictionary' 
```

**Comment by MichaelAquilina** [comment]
Seems related to `g:completor_python_binary`

**Comment by maralla** [comment]
I pushed a commit to fix the error. Please update and try it again.

**Comment by MichaelAquilina** [comment]
That seems to have fixed it :) Thanks for the help!
