### ISSUE TITLE
Erros messages on gitcommit filetype

### ISSUE THREAD

**Issue by gremargus** [maralla/completor.vim#213]
Hi there. I am getting the following error message when I enter the insert mode and type any character on a gitcommit file type:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/Repositories/testing.git/.git/COMMIT_EDITMSG" 8L, 211C
Error detected while processing function <lambda>1[1]..completor#do[1]..<SNR>89_import_python[2]..completor#utils#setup_python:
line    1:
Traceback (most recent call last):
Error detected while processing function <lambda>1[1]..completor#do[1]..<SNR>89_import_python[2]..completor#utils#setup_python:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing function <lambda>1[1]..completor#do[1]..<SNR>89_import_python[2]..completor#utils#setup_python:
line    1:
ImportError: No module named completor
Error detected while processing function <lambda>1[1]..completor#do[9]..completor#utils#get_completer:
line    1:
Traceback (most recent call last):
Error detected while processing function <lambda>1[1]..completor#do[9]..completor#utils#get_completer:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing function <lambda>1[1]..completor#do[9]..completor#utils#get_completer:
line    1:
NameError: name 'completor_api' is not defined
Error detected while processing function <lambda>1[1]..completor#do[9]..completor#utils#get_completer:
line    2:
Traceback (most recent call last):
Error detected while processing function <lambda>1[1]..completor#do[9]..completor#utils#get_completer:
line    2:
  File "<string>", line 1, in <module>
Error detected while processing function <lambda>1[1]..completor#do[9]..completor#utils#get_completer:
line    2:
NameError: name 'res' is not defined
Error detected while processing function <lambda>1[1]..completor#do[9]..completor#utils#get_completer:
line    2:
E858: Eval did not return a valid python object
```
It happens for every character I type in insert mode.

I am using this completor.vim's version:

```
commit d404ceaa8c9ca6e60f8729d9d6ff94c3ceeb43f2 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: maralla <maralla.ai@gmail.com>
Date:   Fri Jul 13 16:02:51 2018 +0800

    Refactored jedi process
```

My vim version:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 22 2018 05:24:30)
macOS version
Included patches: 1-202
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     -ebcdic            -hangul_input      -lua               +mouse_xterm       -python            +tag_binary        +vartabs           -xim
+arabic            +cmdline_hist      +emacs_tags        +iconv             +menu              +multi_byte        +python3           +tag_old_static    +vertsplit         -xpm
+autocmd           +cmdline_info      +eval              +insert_expand     +mksession         +multi_lang        +quickfix          -tag_any_white     +virtualedit       -xsmp
-autoservername    +comments          +ex_extra          +job               +modify_fname      -mzscheme          +reltime           -tcl               +visual            -xterm_clipboard
-balloon_eval      +conceal           +extra_search      +jumplist          +mouse             +netbeans_intg     +rightleft         +termguicolors     +visualextra       -xterm_save
+balloon_eval_term +cryptv            +farsi             +keymap            -mouseshape        +num64             +ruby              +terminal          +viminfo
-browse            +cscope            +file_in_path      +lambda            +mouse_dec         +packages          +scrollbind        +terminfo          +vreplace
++builtin_terms    +cursorbind        +find_in_path      +langmap           -mouse_gpm         +path_extra        +signs             +termresponse      +wildignore
+byte_offset       +cursorshape       +float             +libcall           -mouse_jsbterm     +perl              +smartindent       +textobjects       +wildmenu
+channel           +dialog_con        +folding           +linebreak         +mouse_netterm     +persistent_undo   +startuptime       +timers            +windows
+cindent           +diff              -footer            +lispindent        +mouse_sgr         +postscript        +statusline        +title             +writebackup
-clientserver      +digraphs          +fork()            +listcmds          -mouse_sysmouse    +printer           -sun_workshop      -toolbar           -X11
+clipboard         -dnd               -gettext           +localmap          +mouse_urxvt       +profile           +syntax            +user_commands     -xfontset
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -lic
onv -framework AppKit   -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lut
il -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.5.1 -lobjc
```

My Python version:

```
Python 3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)]
```

This occours only on gitcommit filetype and I have tested on html, css, javascript, php, vim, unix and no ft filetype and I do not know about other filetypes.
I have already commented out all other plugins and it continues to happens.

Can someone give me help?

**Comment by gremargus** [comment]
I have added gitcommit filetype to my blacklist and the errors are now suppressed.

**Comment by kujohn** [comment]
Is there any way to suppress these errors when completors are not found?
There's a use case of editing `hosts` files for ansible playbooks that are yaml type but no extension.

**Comment by maralla** [comment]
Thanks for reporting! The commit b23e8b804664531a1cff2d173048c34c66490e1b suppressed the error messages. Please update.
