### ISSUE TITLE
Error with neco-vim in neovim-qt

### ISSUE THREAD

**Issue by wsdjeg** [maralla/completor.vim#250]
I just have a try with this plugin in neovim-qt in windows 7. but I get following errors:

```


Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
Traceback (most recent call last):
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
  File "<string>", line 1, in <module>
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
  File "C:/Users/Administrator/.cache/vimfiles/repos/github.com/maralla/completor.vim\pythonx\completor\api.py", line 10, in wrapper
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
    return func(vim.bindeval('a:'))
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
  File "C:/Users/Administrator/.cache/vimfiles/repos/github.com/maralla/completor.vim\pythonx\completor\api.py", line 37, in on_data
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
    return c.on_data(args['action'], args['msg']) if c else []
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
  File "C:/Users/Administrator/.cache/vimfiles/repos/github.com/maralla/completor.vim\pythonx\completor\__init__.py", line 227, in on_data
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
    return self.do_complete(data)
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
  File "C:/Users/Administrator/.cache/vimfiles/repos/github.com/maralla/completor.vim\pythonx\completor\__init__.py", line 202, in do_complete
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
    ret.extend(self.parse(data))
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
  File "C:/Users/Administrator/.cache/vimfiles/repos/github.com/kyouryuukunn/completor-necovim\pythonx\completor_vim.py", line 48, in parse
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
    items = list(itertools.islice(itertools.chain(self.gen_entry(kw)), LIMIT))
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
  File "C:/Users/Administrator/.cache/vimfiles/repos/github.com/kyouryuukunn/completor-necovim\pythonx\completor_vim.py", line 25, in gen_entry
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
    score = test_subseq(base, to_unicode(entry['word'], 'utf-8'))
Error detected while processing function <lambda>4[1]..<SNR>309_do_action[8]..completor#action#do[13]..completor#action#callback[7]..<SNR>310_trigger_complete[1]..completor#utils#on_data[1]..provider#python3#Call:
line   18:
KeyError: 'word'
```

I think it is due to plugin `kyouryuukunn/completor-necovim`.

**Comment by maralla** [comment]
This will be fixed by kyouryuukunn/completor-necovim#1.

**Comment by wsdjeg** [comment]
Thanks, good job.
