### ISSUE TITLE
error while complete c++

### ISSUE THREAD

**Issue by wodesuck** [maralla/completor.vim#42]
```
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/wodesuck/.vim/plugged/completor.vim/pythonx/completor/__init__.py", line 121, in get_completions
    return self.parse(base)
  File "/home/wodesuck/.vim/plugged/completor.vim/pythonx/completers/cpp.py", line 66, in parse
    if not item.startswith('COMPLETION:'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

environment:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 24 2016 17:33:26)
Included patches: 1-46
Compiled by Arch Linux
```

**Comment by maralla** [comment]
Pr #44 fixed the problem.

**Comment by wodesuck** [comment]
fixed. thx~
